configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/warp-rankincodes%2Fwarp-hr-6296f9b186eaefb8024bb8ed36bf6fcee617d961d6573edf459b16f8d2aa817d.yml
openapi_spec_hash: cf0ee8d21b63aa9f1f58dfbc2e47d5fc
config_hash: 599b918a4e5ce29219da642bbdf6e191
