configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/warp-rankincodes%2Fwarp-hr-fbc6e46bbea2f6e8921641765156a3d5c5bf94f8b422bce1089bc9decf09fbd9.yml
openapi_spec_hash: bac9bc09ae770dddbc9a8a72daa8e5c6
config_hash: 6ec44bc09a0ce72e3372fdbb4ff94bd0
